/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in EluBackward0. Traceback of forward call that caused the error:
  File "scripts/train.py", line 47, in <module>
    train(args)
  File "scripts/train.py", line 43, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/chenfu/isaac gym/rsl_rl/rsl_rl/runners/on_policy_runner.py", line 257, in learn_vision
    stu_code = self.alg.actor_critic.TCNencoder(obs_student)
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 516, in forward
    return F.elu(input, self.alpha, self.inplace)
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/nn/functional.py", line 1548, in elu
    result = torch._C._nn.elu(input, alpha)
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "scripts/train.py", line 47, in <module>
    train(args)
  File "scripts/train.py", line 43, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/chenfu/isaac gym/rsl_rl/rsl_rl/runners/on_policy_runner.py", line 305, in learn_vision
    depth_actor_loss = self.alg.update_depth_actor(actions_student_buffer, actions_teacher_buffer)
  File "/home/chenfu/isaac gym/rsl_rl/rsl_rl/algorithms/ppo.py", line 147, in update_depth_actor
    loss.backward()
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/chenfu/anaconda3/envs/issac_env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.